# Generated by Django 3.2.7 on 2021-10-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "station_registration_availible",
                    models.BooleanField(default=False, verbose_name="Stations can be registered"),
                ),
                (
                    "api",
                    models.BooleanField(
                        default=False,
                        verbose_name="Does this Tool offer an API Endpoint? (f.ex. to enable a discord bot)",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "semester",
                    models.CharField(
                        choices=[("WS", "Winter semester"), ("SS", "Summer semester")],
                        default="WS",
                        max_length=2,
                        verbose_name="Semester",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Year")),
            ],
            options={
                "ordering": ["year", "semester"],
                "unique_together": {("semester", "year")},
            },
        ),
    ]
