# Generated by Django 3.2.8 on 2021-10-14 20:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_auto_20211014_1745'),
        ('common', '0002_auto_20211012_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='scavenger_hunt_points',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='settings',
            name='scavenger_hunt_secret',
            field=models.CharField(default='SET', max_length=10, verbose_name='Scavenger hunt secret'),
        ),
        migrations.AddField(
            model_name='settings',
            name='scavenger_hunt_station',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratings.station', verbose_name='Scavenger hunt station. If not present a warning will be caused (i.e. scavenger hunt wont be availible)'),
        ),
    ]
