# Generated by Django 3.2.7 on 2021-10-15 06:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0008_auto_20211014_1745"),
        ("common", "0003_auto_20211014_2222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="recaptcha_private_key",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="reCAPTCHA v3 PRIVATE_KEY"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="recaptcha_public_key",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="reCAPTCHA v3 PUBLIC_KEY"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="recaptcha_required_score",
            field=models.FloatField(
                default=0.5,
                verbose_name="reCAPTCHA v3 required score. "
                "(see https://developers.google.com/recaptcha/docs/v3#interpreting_the_score)",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="scavenger_hunt_points",
            field=models.IntegerField(
                default=10,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
                verbose_name="Reward for correctly submitting the scavenger hunt secret",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="scavenger_hunt_secret",
            field=models.CharField(
                default="SET",
                max_length=30,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.MaxLengthValidator(30),
                    django.core.validators.RegexValidator(
                        "[A-Za-z]+$",
                        "Only alphabetic characters, capitalisation is ignored",
                    ),
                ],
                verbose_name="Scavenger hunt secret",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="scavenger_hunt_station",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ratings.station",
                verbose_name="Scavenger hunt station. "
                "If not present a warning will be caused (i.e. scavenger hunt wont be available)",
            ),
        ),
    ]
