# Generated by Django 3.2.7 on 2021-10-23 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20211023_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='scavenger_hunt_secret',
            field=models.CharField(default='SET', max_length=30, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(30), django.core.validators.RegexValidator('[A-Za-z]+$', 'Only alphabetic characters, Capitalisation is ignored')], verbose_name='Scavenger hunt secret'),
        ),
    ]
