# Generated by Django 3.2.7 on 2021-10-03 10:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationToken",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("semester", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="common.semester")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
