# Generated by Django 3.2.8 on 2021-10-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0006_auto_20211012_1757"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="location_description_de",
            field=models.CharField(
                default="Location unknown",
                help_text="Visible on the map",
                max_length=500,
                null=True,
                verbose_name="Description of the Station",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="location_description_en",
            field=models.CharField(
                default="Location unknown",
                help_text="Visible on the map",
                max_length=500,
                null=True,
                verbose_name="Description of the Station",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="name_de",
            field=models.CharField(
                help_text="Visible on the map",
                max_length=150,
                null=True,
                verbose_name="Name of the Station",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="name_en",
            field=models.CharField(
                help_text="Visible on the map",
                max_length=150,
                null=True,
                verbose_name="Name of the Station",
            ),
        ),
    ]
