# Generated by Django 3.2.7 on 2021-10-22 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0008_auto_20211014_1745"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                help_text="Visible on a public leaderboard",
                max_length=30,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.MaxLengthValidator(30),
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9@#$€<>%\\^&+=_\\- äüöß]+$",
                        "Only alphanumeric characters, @#$€<>%%^&+=_-, space and äöüß are allowed",
                    ),
                ],
                verbose_name="Name of your Team",
            ),
        ),
    ]
