# Generated by Django 3.2.7 on 2021-10-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0009_alter_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="contact_person",
            field=models.TextField(default="-", help_text="Displayed to the tutor.", verbose_name="Contact Person"),
        ),
        migrations.AddField(
            model_name="station",
            name="scoring_instructions",
            field=models.TextField(
                default="-",
                help_text="Displayed to the tutor.",
                verbose_name="Instructions, how to score a game.",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="scoring_instructions_de",
            field=models.TextField(
                default="-",
                help_text="Displayed to the tutor.",
                null=True,
                verbose_name="Instructions, how to score a game.",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="scoring_instructions_en",
            field=models.TextField(
                default="-",
                help_text="Displayed to the tutor.",
                null=True,
                verbose_name="Instructions, how to score a game.",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="setup_instructions",
            field=models.TextField(
                default="-",
                help_text="Displayed to the tutor.",
                verbose_name="Instructions, how to setup the station.",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="setup_instructions_de",
            field=models.TextField(
                default="-",
                help_text="Displayed to the tutor.",
                null=True,
                verbose_name="Instructions, how to setup the station.",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="setup_instructions_en",
            field=models.TextField(
                default="-",
                help_text="Displayed to the tutor.",
                null=True,
                verbose_name="Instructions, how to setup the station.",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="setup_tools",
            field=models.TextField(
                default="-",
                help_text="Displayed to the tutor.",
                verbose_name="Utensils/tools needed for this station",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="station_game_instructions",
            field=models.TextField(
                default="-",
                help_text="Displayed to the tutor.",
                verbose_name="Instructions, how to conduct a game.",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="station_game_instructions_de",
            field=models.TextField(
                default="-",
                help_text="Displayed to the tutor.",
                null=True,
                verbose_name="Instructions, how to conduct a game.",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="station_game_instructions_en",
            field=models.TextField(
                default="-",
                help_text="Displayed to the tutor.",
                null=True,
                verbose_name="Instructions, how to conduct a game.",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="tutor_amount",
            field=models.PositiveSmallIntegerField(default=11.671, verbose_name="Longitude of the sation"),
        ),
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.CharField(
                default="Station-name unknown",
                help_text="Visible to logged in users on the map and to tutors",
                max_length=150,
                verbose_name="Name of the Station",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="name_de",
            field=models.CharField(
                default="Station-name unknown",
                help_text="Visible to logged in users on the map and to tutors",
                max_length=150,
                null=True,
                verbose_name="Name of the Station",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="name_en",
            field=models.CharField(
                default="Station-name unknown",
                help_text="Visible to logged in users on the map and to tutors",
                max_length=150,
                null=True,
                verbose_name="Name of the Station",
            ),
        ),
    ]
