# Generated by Django 4.1 on 2022-10-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0012_auto_20211025_1536"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ratingscheme3group",
            unique_together={("handicap", "rating_scheme")},
        ),
    ]
