# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_rallye', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bewertung',
            old_name='st_id',
            new_name='st_token',
        ),
        migrations.RenameField(
            model_name='stand',
            old_name='stand_id',
            new_name='stand_nummer',
        ),
        migrations.RemoveField(
            model_name='laufgruppe',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='id',
        ),
        migrations.AlterField(
            model_name='laufgruppe',
            name='laufgruppen_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stand',
            name='token',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
