# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_rallye', '0002_auto_20170926_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='laufgruppe',
            name='bester_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laufgruppe',
            name='total_punkte',
            field=models.IntegerField(default=0),
        ),
    ]
