# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_rallye', '0003_auto_20170930_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laufgruppe',
            name='laufgruppen_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='laufgruppe',
            name='laufgruppen_name',
            field=models.CharField(default='Laufgruppe', max_length=100),
        ),
        migrations.AlterField(
            model_name='stand',
            name='token',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
